pipeline:
  name: "pipeline_formative_kpi_calc"
  description: "Complete data processing pipeline from preload to final validation"
  env: "${ENV}"  
  schedule_interval: "@daily"
  default_args:
    retries: 2
    retry_delay: "5m"
    params:
      date_9999: "${PROCESSING_DATE}"  # Дата обработки в формате YYYY-MM-DD
      source1: "source_system1"        # Основной источник данных
      source2: "source_system2"        # Дополнительный источник данных
    
  stages:
    stage_preload:
      name: "DATA PRELOAD STAGE"
      description: "Loading source data"
      operator: "python"
      script: "preload.py"
      function: "run"
      dependencies: []
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"

      
    stage_calc_stg:
      name: "STAGING CALCULATION"
      description: "Building staging layer"
      operator: "python"
      script: "calc_stg.py"
      function: "run"
      dependencies: ["stage_preload"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
      
    stage_check_stg:
      name: "STAGING VALIDATION"
      description: "Quality checks"
      operator: "python"
      script: "check_stg.py"
      function: "run"
      dependencies: ["stage_calc_stg"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
      
    stage_calc_inc:
      name: "INCREMENT CALCULATION"
      description: "Processing delta changes"
      operator: "python"
      script: "calc_inc.py"
      function: "calculate"
      dependencies: ["stage_check_stg"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
      
    stage_check_inc:
      name: "INCREMENT VALIDATION"
      description: "Business logic validation"
      operator: "python"
      script: "check_inc.py"
      function: "validate"
      dependencies: ["stage_calc_inc"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
      
    stage_MTP:
      name: "MART TABLE POPULATION"
      description: "Loading mart tables"
      operator: "python"
      script: "mtp.py"
      function: "run"
      dependencies: ["stage_check_inc"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
      
    stage_hist:
      name: "HISTORY UPDATE"
      description: "Updating historical data"
      operator: "python"
      script: "hist.py"
      function: "update"
      dependencies: ["stage_MTP"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
      
    final_check:
      name: "FINAL VALIDATION"
      description: "Comprehensive data validation"
      operator: "python"
      script: "final_checks.py"
      function: "run_all"
      dependencies: ["stage_hist"]
      params:
        query_mapping: "{stg_table: name}"
        datamart: "DataMart_transaction"
        query_path: "hdfs://namenode:8020/sql/dml/kpi_calc/pred_stg_transaction.sql"
        table_schema: "default"
        table_name: "default_table"
        repartition: "40"
        partition_by: "none"
        bucket_by: "none"
        num_buckets: "1"
        location: "hdfs://namenode:8020/user/jenkins/data"
        do_truncate_table: "false"
        do_drop_table: "false"
        do_msck_repair_table: "false"
        temp_view_name: "default_view"
        cache_df: "false"
        