pipeline:
  name: "data_processing_pipeline"
  description: "Complete data processing pipeline from preload to final validation"
  env: "${ENV}"  # Will be replaced with actual environment (dev, prod, etc.)
  schedule_interval: "@daily"
  default_args:
    retries: 2
    retry_delay: "5m"
    params:
      date_9999: "${PROCESSING_DATE}"  # Дата обработки в формате YYYY-MM-DD
      source1: "source_system1"        # Основной источник данных
      source2: "source_system2"        # Дополнительный источник данных
    
  stages:
    stage_preload:
      name: "DATA PRELOAD STAGE"
      description: "Loading source data"
      operator: "python"
      script: "preload.py"
      function: "run"
      dependencies: []
      params:
        source: "{{ params.source1 }}"
        backup_source: "{{ params.source2 }}"
        processing_date: "{{ params.date_9999 }}"
      
    stage_calc_stg:
      name: "STAGING CALCULATION"
      description: "Building staging layer"
      operator: "python"
      script: "calc_stg.py"
      function: "run"
      dependencies: ["stage_preload"]
      params:
        main_source: "{{ params.source1 }}"
        reference_date: "{{ params.date_9999 }}"
      
    stage_check_stg:
      name: "STAGING VALIDATION"
      description: "Quality checks"
      operator: "python"
      script: "check_stg.py"
      function: "run"
      dependencies: ["stage_calc_stg"]
      params:
        source_to_validate: "{{ params.source1 }}"
        secondary_source: "{{ params.source2 }}"
        check_date: "{{ params.date_9999 }}"
      
    stage_calc_inc:
      name: "INCREMENT CALCULATION"
      description: "Processing delta changes"
      operator: "python"
      script: "calc_inc.py"
      function: "calculate"
      dependencies: ["stage_check_stg"]
      params:
        primary_source: "{{ params.source1 }}"
        delta_date: "{{ params.date_9999 }}"
      
    stage_check_inc:
      name: "INCREMENT VALIDATION"
      description: "Business logic validation"
      operator: "python"
      script: "check_inc.py"
      function: "validate"
      dependencies: ["stage_calc_inc"]
      params:
        validation_sources: 
          - "{{ params.source1 }}"
          - "{{ params.source2 }}"
        snapshot_date: "{{ params.date_9999 }}"
      
    stage_MTP:
      name: "MART TABLE POPULATION"
      description: "Loading mart tables"
      operator: "python"
      script: "mtp.py"
      function: "run"
      dependencies: ["stage_check_inc"]
      params:
        data_sources:
          main: "{{ params.source1 }}"
          supplementary: "{{ params.source2 }}"
        load_date: "{{ params.date_9999 }}"
      
    stage_hist:
      name: "HISTORY UPDATE"
      description: "Updating historical data"
      operator: "python"
      script: "hist.py"
      function: "update"
      dependencies: ["stage_MTP"]
      params:
        history_sources:
          - "{{ params.source1 }}"
          - "{{ params.source2 }}"
        effective_date: "{{ params.date_9999 }}"
      
    final_check:
      name: "FINAL VALIDATION"
      description: "Comprehensive data validation"
      operator: "python"
      script: "final_checks.py"
      function: "run_all"
      dependencies: ["stage_hist"]
      params:
        all_sources:
          primary: "{{ params.source1 }}"
          secondary: "{{ params.source2 }}"
        report_date: "{{ params.date_9999 }}"